### ISSUE TITLE
Optimization of error message

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#34]
When the developer does not have enough sepoliaEth to initiate a prove request transaction, the error message is too verbose. Can we catch this error to make it more user-friendly?

### Env
zkgraph-api: v1.0.3
zkgraph-cli: v1.0.0
zkgraph-lib: v1.0.1

### reproduce
1. npm init zkgraph@latest
2. modify zkgraph.config.ts with a low balance account privateKey.
3. try `npm run prove`

and the error log will be like following:
![image](https://github.com/hyperoracle/zkgraph-cli/assets/103174898/efe9598f-03a8-4fe8-a76d-05946f0c2306)

**Comment by lightmanM** [comment]
tracked in the case https://www.notion.so/hyperoracle/Balance-check-and-msg-60b8723619154181b9c593f1fb18a7a8

**Comment by murongg** [comment]
fixed in https://github.com/hyperoracle/zkgraph-api/commit/554015394f08a94a1a918fcd61abb3a8aa86de30
